### ISSUE TITLE
Change the default flag (disconnected status) to a neutral one

### ISSUE THREAD

**Issue by phocean** [growing/gnome-public-ip-extension#4]
Very nice extension, thanks.
However, no offense, but I feel unconfortable to see a U.S flag all the time I am disconnected.
Like many users, I am not a user citizen.
It would be nicer to use a neutral flag (U.N., question mark, etc.).

**Comment by Heimdal300** [comment]
For the Map: Just open .local/share/gnome-shell/extensions/public-ip-address@holdingitwrong.com/icons in your home folder and replace default_map.png with anything you want.

For the small flag:  Open .local/share/gnome-shell/extensions/public-ip-address@holdingitwrong.com/extension.js in your home folder, go to line 127 and replace US.png with anything you want. I used _unknown.png because its already in the icon folder.

**Comment by phocean** [comment]
Yes, it works, thanks :-)
In my opinion, it should be the default.
